### ISSUE TITLE
Java Model Exception: Error in Java Model (code 969): common/common/src/test/java/dev/enola/common/io/resource [in _main] does not exist

### ISSUE THREAD

**Issue by vorburger** [salesforce/bazel-vscode-java#64]
@guw Hi, me again! 😈  Today tried again to use this with https://github.com/enola-dev/enola (with https://github.com/enola-dev/enola/pull/285), to try if #49 did the trick...

It seems like it's definitely much better now, and I now see e.g. _Bazel Build Targets_ in the _Explorer_ - yay!

However it seems like it's still not entirely working; e.g. if I open the [`EmptyResourceTest.java`](https://github.com/enola-dev/enola/blob/main/common/common/src/test/java/dev/enola/common/io/resource/EmptyResourceTest.java) then the class name has a "red squiggle" in the editor, which says _Implicit super constructor Object() is undefined for default constructor. Must define an explicit constructor_ - huh? (It's not finding the JDK, perhaps?)

And the _Output_ for _Language Support for Java_ shows this error, when opening that source file:

```
[Error - 3:31:55 PM] Dec 2, 2023, 3:31:55 PM common/common/src/test/java/dev/enola/common/io/resource [in _main] does not exist
common/common/src/test/java/dev/enola/common/io/resource [in _main] does not exist
Java Model Exception: Error in Java Model (code 969): common/common/src/test/java/dev/enola/common/io/resource [in _main] does not exist
	at org.eclipse.jdt.internal.core.JavaElement.newNotPresentException(JavaElement.java:550)
	at org.eclipse.jdt.internal.core.PackageFragmentRoot.getUnderlyingResource(PackageFragmentRoot.java:761)
	at org.eclipse.jdt.internal.core.PackageFragment.getUnderlyingResource(PackageFragment.java:426)
	at org.eclipse.jdt.internal.core.Openable.getUnderlyingResource(Openable.java:349)
	at org.eclipse.jdt.internal.core.CompilationUnit.getUnderlyingResource(CompilationUnit.java:987)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseDiagnosticsHandler.collectNonJavaProblems(BaseDiagnosticsHandler.java:149)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseDiagnosticsHandler.endReporting(BaseDiagnosticsHandler.java:135)
	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.reportProblems(ReconcileWorkingCopyOperation.java:148)
	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.executeOperation(ReconcileWorkingCopyOperation.java:112)
	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:742)
	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:808)
	at org.eclipse.jdt.internal.core.CompilationUnit.reconcile(CompilationUnit.java:1326)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseDocumentLifeCycleHandler.publishDiagnostics(BaseDocumentLifeCycleHandler.java:326)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseDocumentLifeCycleHandler.publishDiagnostics(BaseDocumentLifeCycleHandler.java:289)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseDocumentLifeCycleHandler$PublishDiagnosticJob.run(BaseDocumentLifeCycleHandler.java:751)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

So looks like some ... "mapping" (?) is still not quite right?

**Comment by guw** [comment]
Thanks for continue trying it and giving feedback @vorburger!

I think we have different issues. I noticed the Java Model Exception in my logs as well but I believe this is an unrelated JDTLS issue. It could indicate a problem in the workflow, i.e. something not available yet. It could also indicate a gap in JDTLS (we are using linked resources/folders heavily).

The other issue (about `EmptyResourceTest`) is a feature gap. We currently do not read in individual `java_test` targets and set them up as source projects. I have been hesitating to do this. It would require creating one Eclipse/Java project per single test class to adhere to the Bazel principles and provide a correct classpath.

As a workaround, try using the[ project-per-package provisioning](https://github.com/salesforce/bazel-eclipse/blob/main/docs/common/projectviews.md#project-per-package) strategy. This is more suitable for Maven like projects at the cost of a more relaxed classpath in the IDEs in contrast to Bazel.

<img width="436" alt="image" src="https://github.com/salesforce/bazel-vscode-java/assets/191472/019fd466-9279-4afe-b4df-8adfa39dabce">

```
cat .eclipse/.bazelproject
directories:
  . 

derive_targets_from_directories: true

target_provisioning_strategy: project-per-package
```
