### ISSUE TITLE
Enola does not initialize anymore after Bazel & other upgrades 

### ISSUE THREAD

**Issue by vorburger** [salesforce/bazel-vscode-java#86]
After many various upgrades in https://github.com/enola-dev/enola, including a Bazel upgrade from 6.4.0 to 7.0.0, and bumping `rules_java` to the latest, and other upgrades, originally all prompted by #85 to be able to try it out under Java 21 ([here](https://github.com/enola-dev/enola/pull/426)), that project even on the `main` branch which currently is still on Java 11 is "all red".

Following https://github.com/salesforce/bazel-vscode-java/blob/main/docs/troubleshoot.md, notably _ Java: Clean Java Language Server Workspace,_ does not help.

Logs: [client.log.2024-01-17.json](https://github.com/salesforce/bazel-vscode-java/files/13959741/client.log.2024-01-17.json) and [log.txt](https://github.com/salesforce/bazel-vscode-java/files/13959756/log.txt)

It says _Failed to find a Bazel workspace_

@guw thought this may interest you?

**Comment by guw** [comment]
Is there any in the Bazel output Terminal?

It looks like your project fails to setup the JRE.
```
!ENTRY org.eclipse.jdt.ls.core 4 0 2024-01-17 07:59:00.633
!MESSAGE Error occured while building workspace. Details: 
 message: The project was not built since its build path is incomplete. Cannot find the class file for java.lang.Object. Fix the build path then try building this project; code: 0; resource: /home/vorburger/git/github.com/enola-dev/enola;
 message: The type java.lang.Object cannot be resolved. It is indirectly referenced from required .class files; code: 16777540; resource: /home/vorburger/git/github.com/enola-dev/enola/cli/src/main/java/dev/enola/cli/CLI.java; line: 1
 ```

**Comment by guw** [comment]
@vorburger I have a stacktrace now testing in Eclipse. Does `:aspect_java_proto_toolchain` ring a bell?

```
2024-01-17 13:07:48,461 [ModalContext] ERROR c.s.b.e.c.m.SynchronizeProjectViewJob - Error synchronizing workspace '/Users/gwagenknecht/Development/oss/enola': Duplicate key :aspect_java_proto_toolchain (attempted merging values name: ":aspect_java_proto_toolchain"
type: LABEL
string_value: "@bazel_tools//tools/proto:java_toolchain"
explicitly_specified: false
nodep: false
 and name: ":aspect_java_proto_toolchain"
type: LABEL
string_value: "@bazel_tools//tools/proto:java_toolchain"
explicitly_specified: false
nodep: false
)
java.lang.IllegalStateException: Duplicate key :aspect_java_proto_toolchain (attempted merging values name: ":aspect_java_proto_toolchain"
type: LABEL
string_value: "@bazel_tools//tools/proto:java_toolchain"
explicitly_specified: false
nodep: false
 and name: ":aspect_java_proto_toolchain"
type: LABEL
string_value: "@bazel_tools//tools/proto:java_toolchain"
explicitly_specified: false
nodep: false
)
	at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:135)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:182)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.salesforce.bazel.eclipse.core.model.BazelRuleAttributes.<init>(BazelRuleAttributes.java:28)
	at com.salesforce.bazel.eclipse.core.model.BazelTargetInfo.getRuleAttributes(BazelTargetInfo.java:118)
	at com.salesforce.bazel.eclipse.core.model.BazelTarget.hasTag(BazelTarget.java:192)
	at com.salesforce.bazel.eclipse.core.model.BazelTarget.isVisibleToIde(BazelTarget.java:202)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at com.salesforce.bazel.eclipse.core.model.discovery.BazelQueryTargetDiscovery.discoverTargets(BazelQueryTargetDiscovery.java:105)
	at com.salesforce.bazel.eclipse.core.model.SynchronizeProjectViewJob.detectTargetsToMaterializeInEclipse(SynchronizeProjectViewJob.java:279)
	at com.salesforce.bazel.eclipse.core.model.SynchronizeProjectViewJob.runInWorkspace(SynchronizeProjectViewJob.java:642)
	at com.salesforce.bazel.eclipse.core.setup.ImportBazelWorkspaceJob.runInWorkspace(ImportBazelWorkspaceJob.java:145)
	at com.salesforce.bazel.eclipse.ui.wizards.BazelImportWizard.lambda$2(BazelImportWizard.java:81)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2453)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2473)
	at com.salesforce.bazel.eclipse.ui.wizards.BazelImportWizard.lambda$1(BazelImportWizard.java:80)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by guw** [comment]
Initial discussion in Bazel slack leads to opening a Bazel bug:
https://github.com/bazelbuild/bazel/issues/20918

**Comment by guw** [comment]
I added a workaround for the problem. Can you try if this solves the problem?
https://github.com/salesforce/bazel-eclipse/commit/ebaebb860edff6cb9f8c6b5ac513741cdd029e20

**Comment by vorburger** [comment]
> I added a workaround for the problem. Can you try if this solves the problem?
https://github.com/salesforce/bazel-eclipse/commit/ebaebb860edff6cb9f8c6b5ac513741cdd029e20

> confirming that with v1.24.101171247

Wait, that doesn't actually include this fix yet, does it? But it's working (again) for me! I'm confused now... 🤣

**Comment by vorburger** [comment]
Looks like it was NOK with `v1.24.101151500` but is now OK (for me) with `v1.24.101171600`.
